services:
  frontend:
    build: ./client
    ports:
      - "3000:80"

  backend:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=3188
      - MYSQL_DATABASE=video_transcoding_db
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 3188
      MYSQL_DATABASE: video_transcoding_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
