# Use an official Node.js runtime as a parent image
FROM node:14

# Set the working directory
WORKDIR /usr/src/app

# Copy the package.json and package-lock.json files
COPY package*.json ./

# Install dependencies
RUN npm install

# Install ffmpeg
RUN apt-get update && apt-get install -y ffmpeg

# Copy the rest of the application code
COPY . .

# Expose the port that the app runs on
EXPOSE 5000

# Start the Node.js application
CMD ["node", "index.js"]
